// Code generated by ent, DO NOT EDIT.

package wechatbindinghistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldUserID, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldAppID, v))
}

// Openid applies equality check predicate on the "openid" field. It's identical to OpenidEQ.
func Openid(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldOpenid, v))
}

// UnboundAt applies equality check predicate on the "unbound_at" field. It's identical to UnboundAtEQ.
func UnboundAt(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldUnboundAt, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLTE(FieldUserID, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLTE(FieldAppID, v))
}

// AppIDContains applies the Contains predicate on the "app_id" field.
func AppIDContains(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldContains(FieldAppID, v))
}

// AppIDHasPrefix applies the HasPrefix predicate on the "app_id" field.
func AppIDHasPrefix(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldHasPrefix(FieldAppID, v))
}

// AppIDHasSuffix applies the HasSuffix predicate on the "app_id" field.
func AppIDHasSuffix(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldHasSuffix(FieldAppID, v))
}

// AppIDEqualFold applies the EqualFold predicate on the "app_id" field.
func AppIDEqualFold(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEqualFold(FieldAppID, v))
}

// AppIDContainsFold applies the ContainsFold predicate on the "app_id" field.
func AppIDContainsFold(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldContainsFold(FieldAppID, v))
}

// OpenidEQ applies the EQ predicate on the "openid" field.
func OpenidEQ(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldOpenid, v))
}

// OpenidNEQ applies the NEQ predicate on the "openid" field.
func OpenidNEQ(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNEQ(FieldOpenid, v))
}

// OpenidIn applies the In predicate on the "openid" field.
func OpenidIn(vs ...string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldIn(FieldOpenid, vs...))
}

// OpenidNotIn applies the NotIn predicate on the "openid" field.
func OpenidNotIn(vs ...string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNotIn(FieldOpenid, vs...))
}

// OpenidGT applies the GT predicate on the "openid" field.
func OpenidGT(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGT(FieldOpenid, v))
}

// OpenidGTE applies the GTE predicate on the "openid" field.
func OpenidGTE(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGTE(FieldOpenid, v))
}

// OpenidLT applies the LT predicate on the "openid" field.
func OpenidLT(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLT(FieldOpenid, v))
}

// OpenidLTE applies the LTE predicate on the "openid" field.
func OpenidLTE(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLTE(FieldOpenid, v))
}

// OpenidContains applies the Contains predicate on the "openid" field.
func OpenidContains(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldContains(FieldOpenid, v))
}

// OpenidHasPrefix applies the HasPrefix predicate on the "openid" field.
func OpenidHasPrefix(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldHasPrefix(FieldOpenid, v))
}

// OpenidHasSuffix applies the HasSuffix predicate on the "openid" field.
func OpenidHasSuffix(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldHasSuffix(FieldOpenid, v))
}

// OpenidEqualFold applies the EqualFold predicate on the "openid" field.
func OpenidEqualFold(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEqualFold(FieldOpenid, v))
}

// OpenidContainsFold applies the ContainsFold predicate on the "openid" field.
func OpenidContainsFold(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldContainsFold(FieldOpenid, v))
}

// UnboundAtEQ applies the EQ predicate on the "unbound_at" field.
func UnboundAtEQ(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldUnboundAt, v))
}

// UnboundAtNEQ applies the NEQ predicate on the "unbound_at" field.
func UnboundAtNEQ(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNEQ(FieldUnboundAt, v))
}

// UnboundAtIn applies the In predicate on the "unbound_at" field.
func UnboundAtIn(vs ...time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldIn(FieldUnboundAt, vs...))
}

// UnboundAtNotIn applies the NotIn predicate on the "unbound_at" field.
func UnboundAtNotIn(vs ...time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNotIn(FieldUnboundAt, vs...))
}

// UnboundAtGT applies the GT predicate on the "unbound_at" field.
func UnboundAtGT(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGT(FieldUnboundAt, v))
}

// UnboundAtGTE applies the GTE predicate on the "unbound_at" field.
func UnboundAtGTE(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGTE(FieldUnboundAt, v))
}

// UnboundAtLT applies the LT predicate on the "unbound_at" field.
func UnboundAtLT(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLT(FieldUnboundAt, v))
}

// UnboundAtLTE applies the LTE predicate on the "unbound_at" field.
func UnboundAtLTE(v time.Time) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLTE(FieldUnboundAt, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.FieldContainsFold(FieldReason, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WeChatBindingHistory) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WeChatBindingHistory) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WeChatBindingHistory) predicate.WeChatBindingHistory {
	return predicate.WeChatBindingHistory(sql.NotPredicates(p))
}
