// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/wechatbindinghistory"
)

// WeChatBindingHistoryCreate is the builder for creating a WeChatBindingHistory entity.
type WeChatBindingHistoryCreate struct {
	config
	mutation *WeChatBindingHistoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *WeChatBindingHistoryCreate) SetCreatedAt(v time.Time) *WeChatBindingHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WeChatBindingHistoryCreate) SetNillableCreatedAt(v *time.Time) *WeChatBindingHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WeChatBindingHistoryCreate) SetUpdatedAt(v time.Time) *WeChatBindingHistoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WeChatBindingHistoryCreate) SetNillableUpdatedAt(v *time.Time) *WeChatBindingHistoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *WeChatBindingHistoryCreate) SetUserID(v int64) *WeChatBindingHistoryCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *WeChatBindingHistoryCreate) SetAppID(v string) *WeChatBindingHistoryCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetOpenid sets the "openid" field.
func (_c *WeChatBindingHistoryCreate) SetOpenid(v string) *WeChatBindingHistoryCreate {
	_c.mutation.SetOpenid(v)
	return _c
}

// SetUnboundAt sets the "unbound_at" field.
func (_c *WeChatBindingHistoryCreate) SetUnboundAt(v time.Time) *WeChatBindingHistoryCreate {
	_c.mutation.SetUnboundAt(v)
	return _c
}

// SetNillableUnboundAt sets the "unbound_at" field if the given value is not nil.
func (_c *WeChatBindingHistoryCreate) SetNillableUnboundAt(v *time.Time) *WeChatBindingHistoryCreate {
	if v != nil {
		_c.SetUnboundAt(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *WeChatBindingHistoryCreate) SetReason(v string) *WeChatBindingHistoryCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *WeChatBindingHistoryCreate) SetNillableReason(v *string) *WeChatBindingHistoryCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// Mutation returns the WeChatBindingHistoryMutation object of the builder.
func (_c *WeChatBindingHistoryCreate) Mutation() *WeChatBindingHistoryMutation {
	return _c.mutation
}

// Save creates the WeChatBindingHistory in the database.
func (_c *WeChatBindingHistoryCreate) Save(ctx context.Context) (*WeChatBindingHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WeChatBindingHistoryCreate) SaveX(ctx context.Context) *WeChatBindingHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WeChatBindingHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WeChatBindingHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WeChatBindingHistoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := wechatbindinghistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := wechatbindinghistory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UnboundAt(); !ok {
		v := wechatbindinghistory.DefaultUnboundAt()
		_c.mutation.SetUnboundAt(v)
	}
	if _, ok := _c.mutation.Reason(); !ok {
		v := wechatbindinghistory.DefaultReason
		_c.mutation.SetReason(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WeChatBindingHistoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WeChatBindingHistory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WeChatBindingHistory.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WeChatBindingHistory.user_id"`)}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "WeChatBindingHistory.app_id"`)}
	}
	if v, ok := _c.mutation.AppID(); ok {
		if err := wechatbindinghistory.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "WeChatBindingHistory.app_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Openid(); !ok {
		return &ValidationError{Name: "openid", err: errors.New(`ent: missing required field "WeChatBindingHistory.openid"`)}
	}
	if v, ok := _c.mutation.Openid(); ok {
		if err := wechatbindinghistory.OpenidValidator(v); err != nil {
			return &ValidationError{Name: "openid", err: fmt.Errorf(`ent: validator failed for field "WeChatBindingHistory.openid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UnboundAt(); !ok {
		return &ValidationError{Name: "unbound_at", err: errors.New(`ent: missing required field "WeChatBindingHistory.unbound_at"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "WeChatBindingHistory.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := wechatbindinghistory.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "WeChatBindingHistory.reason": %w`, err)}
		}
	}
	return nil
}

func (_c *WeChatBindingHistoryCreate) sqlSave(ctx context.Context) (*WeChatBindingHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WeChatBindingHistoryCreate) createSpec() (*WeChatBindingHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &WeChatBindingHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wechatbindinghistory.Table, sqlgraph.NewFieldSpec(wechatbindinghistory.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(wechatbindinghistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(wechatbindinghistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(wechatbindinghistory.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(wechatbindinghistory.FieldAppID, field.TypeString, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.Openid(); ok {
		_spec.SetField(wechatbindinghistory.FieldOpenid, field.TypeString, value)
		_node.Openid = value
	}
	if value, ok := _c.mutation.UnboundAt(); ok {
		_spec.SetField(wechatbindinghistory.FieldUnboundAt, field.TypeTime, value)
		_node.UnboundAt = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(wechatbindinghistory.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WeChatBindingHistory.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WeChatBindingHistoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WeChatBindingHistoryCreate) OnConflict(opts ...sql.ConflictOption) *WeChatBindingHistoryUpsertOne {
	_c.conflict = opts
	return &WeChatBindingHistoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WeChatBindingHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WeChatBindingHistoryCreate) OnConflictColumns(columns ...string) *WeChatBindingHistoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WeChatBindingHistoryUpsertOne{
		create: _c,
	}
}

type (
	// WeChatBindingHistoryUpsertOne is the builder for "upsert"-ing
	//  one WeChatBindingHistory node.
	WeChatBindingHistoryUpsertOne struct {
		create *WeChatBindingHistoryCreate
	}

	// WeChatBindingHistoryUpsert is the "OnConflict" setter.
	WeChatBindingHistoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *WeChatBindingHistoryUpsert) SetUpdatedAt(v time.Time) *WeChatBindingHistoryUpsert {
	u.Set(wechatbindinghistory.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsert) UpdateUpdatedAt() *WeChatBindingHistoryUpsert {
	u.SetExcluded(wechatbindinghistory.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *WeChatBindingHistoryUpsert) SetUserID(v int64) *WeChatBindingHistoryUpsert {
	u.Set(wechatbindinghistory.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsert) UpdateUserID() *WeChatBindingHistoryUpsert {
	u.SetExcluded(wechatbindinghistory.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *WeChatBindingHistoryUpsert) AddUserID(v int64) *WeChatBindingHistoryUpsert {
	u.Add(wechatbindinghistory.FieldUserID, v)
	return u
}

// SetAppID sets the "app_id" field.
func (u *WeChatBindingHistoryUpsert) SetAppID(v string) *WeChatBindingHistoryUpsert {
	u.Set(wechatbindinghistory.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsert) UpdateAppID() *WeChatBindingHistoryUpsert {
	u.SetExcluded(wechatbindinghistory.FieldAppID)
	return u
}

// SetOpenid sets the "openid" field.
func (u *WeChatBindingHistoryUpsert) SetOpenid(v string) *WeChatBindingHistoryUpsert {
	u.Set(wechatbindinghistory.FieldOpenid, v)
	return u
}

// UpdateOpenid sets the "openid" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsert) UpdateOpenid() *WeChatBindingHistoryUpsert {
	u.SetExcluded(wechatbindinghistory.FieldOpenid)
	return u
}

// SetUnboundAt sets the "unbound_at" field.
func (u *WeChatBindingHistoryUpsert) SetUnboundAt(v time.Time) *WeChatBindingHistoryUpsert {
	u.Set(wechatbindinghistory.FieldUnboundAt, v)
	return u
}

// UpdateUnboundAt sets the "unbound_at" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsert) UpdateUnboundAt() *WeChatBindingHistoryUpsert {
	u.SetExcluded(wechatbindinghistory.FieldUnboundAt)
	return u
}

// SetReason sets the "reason" field.
func (u *WeChatBindingHistoryUpsert) SetReason(v string) *WeChatBindingHistoryUpsert {
	u.Set(wechatbindinghistory.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsert) UpdateReason() *WeChatBindingHistoryUpsert {
	u.SetExcluded(wechatbindinghistory.FieldReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WeChatBindingHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WeChatBindingHistoryUpsertOne) UpdateNewValues() *WeChatBindingHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(wechatbindinghistory.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WeChatBindingHistory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WeChatBindingHistoryUpsertOne) Ignore() *WeChatBindingHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WeChatBindingHistoryUpsertOne) DoNothing() *WeChatBindingHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WeChatBindingHistoryCreate.OnConflict
// documentation for more info.
func (u *WeChatBindingHistoryUpsertOne) Update(set func(*WeChatBindingHistoryUpsert)) *WeChatBindingHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WeChatBindingHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WeChatBindingHistoryUpsertOne) SetUpdatedAt(v time.Time) *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertOne) UpdateUpdatedAt() *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *WeChatBindingHistoryUpsertOne) SetUserID(v int64) *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WeChatBindingHistoryUpsertOne) AddUserID(v int64) *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertOne) UpdateUserID() *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateUserID()
	})
}

// SetAppID sets the "app_id" field.
func (u *WeChatBindingHistoryUpsertOne) SetAppID(v string) *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertOne) UpdateAppID() *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateAppID()
	})
}

// SetOpenid sets the "openid" field.
func (u *WeChatBindingHistoryUpsertOne) SetOpenid(v string) *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetOpenid(v)
	})
}

// UpdateOpenid sets the "openid" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertOne) UpdateOpenid() *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateOpenid()
	})
}

// SetUnboundAt sets the "unbound_at" field.
func (u *WeChatBindingHistoryUpsertOne) SetUnboundAt(v time.Time) *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetUnboundAt(v)
	})
}

// UpdateUnboundAt sets the "unbound_at" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertOne) UpdateUnboundAt() *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateUnboundAt()
	})
}

// SetReason sets the "reason" field.
func (u *WeChatBindingHistoryUpsertOne) SetReason(v string) *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertOne) UpdateReason() *WeChatBindingHistoryUpsertOne {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateReason()
	})
}

// Exec executes the query.
func (u *WeChatBindingHistoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WeChatBindingHistoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WeChatBindingHistoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WeChatBindingHistoryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WeChatBindingHistoryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WeChatBindingHistoryCreateBulk is the builder for creating many WeChatBindingHistory entities in bulk.
type WeChatBindingHistoryCreateBulk struct {
	config
	err      error
	builders []*WeChatBindingHistoryCreate
	conflict []sql.ConflictOption
}

// Save creates the WeChatBindingHistory entities in the database.
func (_c *WeChatBindingHistoryCreateBulk) Save(ctx context.Context) ([]*WeChatBindingHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WeChatBindingHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WeChatBindingHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WeChatBindingHistoryCreateBulk) SaveX(ctx context.Context) []*WeChatBindingHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WeChatBindingHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WeChatBindingHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WeChatBindingHistory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WeChatBindingHistoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WeChatBindingHistoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *WeChatBindingHistoryUpsertBulk {
	_c.conflict = opts
	return &WeChatBindingHistoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WeChatBindingHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WeChatBindingHistoryCreateBulk) OnConflictColumns(columns ...string) *WeChatBindingHistoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WeChatBindingHistoryUpsertBulk{
		create: _c,
	}
}

// WeChatBindingHistoryUpsertBulk is the builder for "upsert"-ing
// a bulk of WeChatBindingHistory nodes.
type WeChatBindingHistoryUpsertBulk struct {
	create *WeChatBindingHistoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WeChatBindingHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WeChatBindingHistoryUpsertBulk) UpdateNewValues() *WeChatBindingHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(wechatbindinghistory.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WeChatBindingHistory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WeChatBindingHistoryUpsertBulk) Ignore() *WeChatBindingHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WeChatBindingHistoryUpsertBulk) DoNothing() *WeChatBindingHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WeChatBindingHistoryCreateBulk.OnConflict
// documentation for more info.
func (u *WeChatBindingHistoryUpsertBulk) Update(set func(*WeChatBindingHistoryUpsert)) *WeChatBindingHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WeChatBindingHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WeChatBindingHistoryUpsertBulk) SetUpdatedAt(v time.Time) *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertBulk) UpdateUpdatedAt() *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *WeChatBindingHistoryUpsertBulk) SetUserID(v int64) *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WeChatBindingHistoryUpsertBulk) AddUserID(v int64) *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertBulk) UpdateUserID() *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateUserID()
	})
}

// SetAppID sets the "app_id" field.
func (u *WeChatBindingHistoryUpsertBulk) SetAppID(v string) *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertBulk) UpdateAppID() *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateAppID()
	})
}

// SetOpenid sets the "openid" field.
func (u *WeChatBindingHistoryUpsertBulk) SetOpenid(v string) *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetOpenid(v)
	})
}

// UpdateOpenid sets the "openid" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertBulk) UpdateOpenid() *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateOpenid()
	})
}

// SetUnboundAt sets the "unbound_at" field.
func (u *WeChatBindingHistoryUpsertBulk) SetUnboundAt(v time.Time) *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetUnboundAt(v)
	})
}

// UpdateUnboundAt sets the "unbound_at" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertBulk) UpdateUnboundAt() *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateUnboundAt()
	})
}

// SetReason sets the "reason" field.
func (u *WeChatBindingHistoryUpsertBulk) SetReason(v string) *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *WeChatBindingHistoryUpsertBulk) UpdateReason() *WeChatBindingHistoryUpsertBulk {
	return u.Update(func(s *WeChatBindingHistoryUpsert) {
		s.UpdateReason()
	})
}

// Exec executes the query.
func (u *WeChatBindingHistoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WeChatBindingHistoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WeChatBindingHistoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WeChatBindingHistoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
