// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/wechatbinding"
)

// WeChatBindingUpdate is the builder for updating WeChatBinding entities.
type WeChatBindingUpdate struct {
	config
	hooks    []Hook
	mutation *WeChatBindingMutation
}

// Where appends a list predicates to the WeChatBindingUpdate builder.
func (_u *WeChatBindingUpdate) Where(ps ...predicate.WeChatBinding) *WeChatBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WeChatBindingUpdate) SetUpdatedAt(v time.Time) *WeChatBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WeChatBindingUpdate) SetUserID(v int64) *WeChatBindingUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WeChatBindingUpdate) SetNillableUserID(v *int64) *WeChatBindingUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *WeChatBindingUpdate) SetAppID(v string) *WeChatBindingUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *WeChatBindingUpdate) SetNillableAppID(v *string) *WeChatBindingUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetOpenid sets the "openid" field.
func (_u *WeChatBindingUpdate) SetOpenid(v string) *WeChatBindingUpdate {
	_u.mutation.SetOpenid(v)
	return _u
}

// SetNillableOpenid sets the "openid" field if the given value is not nil.
func (_u *WeChatBindingUpdate) SetNillableOpenid(v *string) *WeChatBindingUpdate {
	if v != nil {
		_u.SetOpenid(*v)
	}
	return _u
}

// SetUnionid sets the "unionid" field.
func (_u *WeChatBindingUpdate) SetUnionid(v string) *WeChatBindingUpdate {
	_u.mutation.SetUnionid(v)
	return _u
}

// SetNillableUnionid sets the "unionid" field if the given value is not nil.
func (_u *WeChatBindingUpdate) SetNillableUnionid(v *string) *WeChatBindingUpdate {
	if v != nil {
		_u.SetUnionid(*v)
	}
	return _u
}

// ClearUnionid clears the value of the "unionid" field.
func (_u *WeChatBindingUpdate) ClearUnionid() *WeChatBindingUpdate {
	_u.mutation.ClearUnionid()
	return _u
}

// SetSubscribed sets the "subscribed" field.
func (_u *WeChatBindingUpdate) SetSubscribed(v bool) *WeChatBindingUpdate {
	_u.mutation.SetSubscribed(v)
	return _u
}

// SetNillableSubscribed sets the "subscribed" field if the given value is not nil.
func (_u *WeChatBindingUpdate) SetNillableSubscribed(v *bool) *WeChatBindingUpdate {
	if v != nil {
		_u.SetSubscribed(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WeChatBindingUpdate) SetUser(v *User) *WeChatBindingUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the WeChatBindingMutation object of the builder.
func (_u *WeChatBindingUpdate) Mutation() *WeChatBindingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WeChatBindingUpdate) ClearUser() *WeChatBindingUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WeChatBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WeChatBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WeChatBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WeChatBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WeChatBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wechatbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WeChatBindingUpdate) check() error {
	if v, ok := _u.mutation.AppID(); ok {
		if err := wechatbinding.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "WeChatBinding.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Openid(); ok {
		if err := wechatbinding.OpenidValidator(v); err != nil {
			return &ValidationError{Name: "openid", err: fmt.Errorf(`ent: validator failed for field "WeChatBinding.openid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Unionid(); ok {
		if err := wechatbinding.UnionidValidator(v); err != nil {
			return &ValidationError{Name: "unionid", err: fmt.Errorf(`ent: validator failed for field "WeChatBinding.unionid": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WeChatBinding.user"`)
	}
	return nil
}

func (_u *WeChatBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wechatbinding.Table, wechatbinding.Columns, sqlgraph.NewFieldSpec(wechatbinding.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wechatbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(wechatbinding.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Openid(); ok {
		_spec.SetField(wechatbinding.FieldOpenid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Unionid(); ok {
		_spec.SetField(wechatbinding.FieldUnionid, field.TypeString, value)
	}
	if _u.mutation.UnionidCleared() {
		_spec.ClearField(wechatbinding.FieldUnionid, field.TypeString)
	}
	if value, ok := _u.mutation.Subscribed(); ok {
		_spec.SetField(wechatbinding.FieldSubscribed, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wechatbinding.UserTable,
			Columns: []string{wechatbinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wechatbinding.UserTable,
			Columns: []string{wechatbinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wechatbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WeChatBindingUpdateOne is the builder for updating a single WeChatBinding entity.
type WeChatBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WeChatBindingMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WeChatBindingUpdateOne) SetUpdatedAt(v time.Time) *WeChatBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WeChatBindingUpdateOne) SetUserID(v int64) *WeChatBindingUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WeChatBindingUpdateOne) SetNillableUserID(v *int64) *WeChatBindingUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *WeChatBindingUpdateOne) SetAppID(v string) *WeChatBindingUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *WeChatBindingUpdateOne) SetNillableAppID(v *string) *WeChatBindingUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetOpenid sets the "openid" field.
func (_u *WeChatBindingUpdateOne) SetOpenid(v string) *WeChatBindingUpdateOne {
	_u.mutation.SetOpenid(v)
	return _u
}

// SetNillableOpenid sets the "openid" field if the given value is not nil.
func (_u *WeChatBindingUpdateOne) SetNillableOpenid(v *string) *WeChatBindingUpdateOne {
	if v != nil {
		_u.SetOpenid(*v)
	}
	return _u
}

// SetUnionid sets the "unionid" field.
func (_u *WeChatBindingUpdateOne) SetUnionid(v string) *WeChatBindingUpdateOne {
	_u.mutation.SetUnionid(v)
	return _u
}

// SetNillableUnionid sets the "unionid" field if the given value is not nil.
func (_u *WeChatBindingUpdateOne) SetNillableUnionid(v *string) *WeChatBindingUpdateOne {
	if v != nil {
		_u.SetUnionid(*v)
	}
	return _u
}

// ClearUnionid clears the value of the "unionid" field.
func (_u *WeChatBindingUpdateOne) ClearUnionid() *WeChatBindingUpdateOne {
	_u.mutation.ClearUnionid()
	return _u
}

// SetSubscribed sets the "subscribed" field.
func (_u *WeChatBindingUpdateOne) SetSubscribed(v bool) *WeChatBindingUpdateOne {
	_u.mutation.SetSubscribed(v)
	return _u
}

// SetNillableSubscribed sets the "subscribed" field if the given value is not nil.
func (_u *WeChatBindingUpdateOne) SetNillableSubscribed(v *bool) *WeChatBindingUpdateOne {
	if v != nil {
		_u.SetSubscribed(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WeChatBindingUpdateOne) SetUser(v *User) *WeChatBindingUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the WeChatBindingMutation object of the builder.
func (_u *WeChatBindingUpdateOne) Mutation() *WeChatBindingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WeChatBindingUpdateOne) ClearUser() *WeChatBindingUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the WeChatBindingUpdate builder.
func (_u *WeChatBindingUpdateOne) Where(ps ...predicate.WeChatBinding) *WeChatBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WeChatBindingUpdateOne) Select(field string, fields ...string) *WeChatBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WeChatBinding entity.
func (_u *WeChatBindingUpdateOne) Save(ctx context.Context) (*WeChatBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WeChatBindingUpdateOne) SaveX(ctx context.Context) *WeChatBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WeChatBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WeChatBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WeChatBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wechatbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WeChatBindingUpdateOne) check() error {
	if v, ok := _u.mutation.AppID(); ok {
		if err := wechatbinding.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "WeChatBinding.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Openid(); ok {
		if err := wechatbinding.OpenidValidator(v); err != nil {
			return &ValidationError{Name: "openid", err: fmt.Errorf(`ent: validator failed for field "WeChatBinding.openid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Unionid(); ok {
		if err := wechatbinding.UnionidValidator(v); err != nil {
			return &ValidationError{Name: "unionid", err: fmt.Errorf(`ent: validator failed for field "WeChatBinding.unionid": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WeChatBinding.user"`)
	}
	return nil
}

func (_u *WeChatBindingUpdateOne) sqlSave(ctx context.Context) (_node *WeChatBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wechatbinding.Table, wechatbinding.Columns, sqlgraph.NewFieldSpec(wechatbinding.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WeChatBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wechatbinding.FieldID)
		for _, f := range fields {
			if !wechatbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wechatbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wechatbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(wechatbinding.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Openid(); ok {
		_spec.SetField(wechatbinding.FieldOpenid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Unionid(); ok {
		_spec.SetField(wechatbinding.FieldUnionid, field.TypeString, value)
	}
	if _u.mutation.UnionidCleared() {
		_spec.ClearField(wechatbinding.FieldUnionid, field.TypeString)
	}
	if value, ok := _u.mutation.Subscribed(); ok {
		_spec.SetField(wechatbinding.FieldSubscribed, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wechatbinding.UserTable,
			Columns: []string{wechatbinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wechatbinding.UserTable,
			Columns: []string{wechatbinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WeChatBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wechatbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
