// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/wechatbinding"
)

// WeChatBindingCreate is the builder for creating a WeChatBinding entity.
type WeChatBindingCreate struct {
	config
	mutation *WeChatBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *WeChatBindingCreate) SetCreatedAt(v time.Time) *WeChatBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WeChatBindingCreate) SetNillableCreatedAt(v *time.Time) *WeChatBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WeChatBindingCreate) SetUpdatedAt(v time.Time) *WeChatBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WeChatBindingCreate) SetNillableUpdatedAt(v *time.Time) *WeChatBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *WeChatBindingCreate) SetUserID(v int64) *WeChatBindingCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *WeChatBindingCreate) SetAppID(v string) *WeChatBindingCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetOpenid sets the "openid" field.
func (_c *WeChatBindingCreate) SetOpenid(v string) *WeChatBindingCreate {
	_c.mutation.SetOpenid(v)
	return _c
}

// SetUnionid sets the "unionid" field.
func (_c *WeChatBindingCreate) SetUnionid(v string) *WeChatBindingCreate {
	_c.mutation.SetUnionid(v)
	return _c
}

// SetNillableUnionid sets the "unionid" field if the given value is not nil.
func (_c *WeChatBindingCreate) SetNillableUnionid(v *string) *WeChatBindingCreate {
	if v != nil {
		_c.SetUnionid(*v)
	}
	return _c
}

// SetSubscribed sets the "subscribed" field.
func (_c *WeChatBindingCreate) SetSubscribed(v bool) *WeChatBindingCreate {
	_c.mutation.SetSubscribed(v)
	return _c
}

// SetNillableSubscribed sets the "subscribed" field if the given value is not nil.
func (_c *WeChatBindingCreate) SetNillableSubscribed(v *bool) *WeChatBindingCreate {
	if v != nil {
		_c.SetSubscribed(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *WeChatBindingCreate) SetUser(v *User) *WeChatBindingCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the WeChatBindingMutation object of the builder.
func (_c *WeChatBindingCreate) Mutation() *WeChatBindingMutation {
	return _c.mutation
}

// Save creates the WeChatBinding in the database.
func (_c *WeChatBindingCreate) Save(ctx context.Context) (*WeChatBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WeChatBindingCreate) SaveX(ctx context.Context) *WeChatBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WeChatBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WeChatBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WeChatBindingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := wechatbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := wechatbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Subscribed(); !ok {
		v := wechatbinding.DefaultSubscribed
		_c.mutation.SetSubscribed(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WeChatBindingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WeChatBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WeChatBinding.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WeChatBinding.user_id"`)}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "WeChatBinding.app_id"`)}
	}
	if v, ok := _c.mutation.AppID(); ok {
		if err := wechatbinding.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "WeChatBinding.app_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Openid(); !ok {
		return &ValidationError{Name: "openid", err: errors.New(`ent: missing required field "WeChatBinding.openid"`)}
	}
	if v, ok := _c.mutation.Openid(); ok {
		if err := wechatbinding.OpenidValidator(v); err != nil {
			return &ValidationError{Name: "openid", err: fmt.Errorf(`ent: validator failed for field "WeChatBinding.openid": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Unionid(); ok {
		if err := wechatbinding.UnionidValidator(v); err != nil {
			return &ValidationError{Name: "unionid", err: fmt.Errorf(`ent: validator failed for field "WeChatBinding.unionid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subscribed(); !ok {
		return &ValidationError{Name: "subscribed", err: errors.New(`ent: missing required field "WeChatBinding.subscribed"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "WeChatBinding.user"`)}
	}
	return nil
}

func (_c *WeChatBindingCreate) sqlSave(ctx context.Context) (*WeChatBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WeChatBindingCreate) createSpec() (*WeChatBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &WeChatBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wechatbinding.Table, sqlgraph.NewFieldSpec(wechatbinding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(wechatbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(wechatbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(wechatbinding.FieldAppID, field.TypeString, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.Openid(); ok {
		_spec.SetField(wechatbinding.FieldOpenid, field.TypeString, value)
		_node.Openid = value
	}
	if value, ok := _c.mutation.Unionid(); ok {
		_spec.SetField(wechatbinding.FieldUnionid, field.TypeString, value)
		_node.Unionid = &value
	}
	if value, ok := _c.mutation.Subscribed(); ok {
		_spec.SetField(wechatbinding.FieldSubscribed, field.TypeBool, value)
		_node.Subscribed = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wechatbinding.UserTable,
			Columns: []string{wechatbinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WeChatBinding.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WeChatBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WeChatBindingCreate) OnConflict(opts ...sql.ConflictOption) *WeChatBindingUpsertOne {
	_c.conflict = opts
	return &WeChatBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WeChatBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WeChatBindingCreate) OnConflictColumns(columns ...string) *WeChatBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WeChatBindingUpsertOne{
		create: _c,
	}
}

type (
	// WeChatBindingUpsertOne is the builder for "upsert"-ing
	//  one WeChatBinding node.
	WeChatBindingUpsertOne struct {
		create *WeChatBindingCreate
	}

	// WeChatBindingUpsert is the "OnConflict" setter.
	WeChatBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *WeChatBindingUpsert) SetUpdatedAt(v time.Time) *WeChatBindingUpsert {
	u.Set(wechatbinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WeChatBindingUpsert) UpdateUpdatedAt() *WeChatBindingUpsert {
	u.SetExcluded(wechatbinding.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *WeChatBindingUpsert) SetUserID(v int64) *WeChatBindingUpsert {
	u.Set(wechatbinding.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WeChatBindingUpsert) UpdateUserID() *WeChatBindingUpsert {
	u.SetExcluded(wechatbinding.FieldUserID)
	return u
}

// SetAppID sets the "app_id" field.
func (u *WeChatBindingUpsert) SetAppID(v string) *WeChatBindingUpsert {
	u.Set(wechatbinding.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *WeChatBindingUpsert) UpdateAppID() *WeChatBindingUpsert {
	u.SetExcluded(wechatbinding.FieldAppID)
	return u
}

// SetOpenid sets the "openid" field.
func (u *WeChatBindingUpsert) SetOpenid(v string) *WeChatBindingUpsert {
	u.Set(wechatbinding.FieldOpenid, v)
	return u
}

// UpdateOpenid sets the "openid" field to the value that was provided on create.
func (u *WeChatBindingUpsert) UpdateOpenid() *WeChatBindingUpsert {
	u.SetExcluded(wechatbinding.FieldOpenid)
	return u
}

// SetUnionid sets the "unionid" field.
func (u *WeChatBindingUpsert) SetUnionid(v string) *WeChatBindingUpsert {
	u.Set(wechatbinding.FieldUnionid, v)
	return u
}

// UpdateUnionid sets the "unionid" field to the value that was provided on create.
func (u *WeChatBindingUpsert) UpdateUnionid() *WeChatBindingUpsert {
	u.SetExcluded(wechatbinding.FieldUnionid)
	return u
}

// ClearUnionid clears the value of the "unionid" field.
func (u *WeChatBindingUpsert) ClearUnionid() *WeChatBindingUpsert {
	u.SetNull(wechatbinding.FieldUnionid)
	return u
}

// SetSubscribed sets the "subscribed" field.
func (u *WeChatBindingUpsert) SetSubscribed(v bool) *WeChatBindingUpsert {
	u.Set(wechatbinding.FieldSubscribed, v)
	return u
}

// UpdateSubscribed sets the "subscribed" field to the value that was provided on create.
func (u *WeChatBindingUpsert) UpdateSubscribed() *WeChatBindingUpsert {
	u.SetExcluded(wechatbinding.FieldSubscribed)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WeChatBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WeChatBindingUpsertOne) UpdateNewValues() *WeChatBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(wechatbinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WeChatBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WeChatBindingUpsertOne) Ignore() *WeChatBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WeChatBindingUpsertOne) DoNothing() *WeChatBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WeChatBindingCreate.OnConflict
// documentation for more info.
func (u *WeChatBindingUpsertOne) Update(set func(*WeChatBindingUpsert)) *WeChatBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WeChatBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WeChatBindingUpsertOne) SetUpdatedAt(v time.Time) *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WeChatBindingUpsertOne) UpdateUpdatedAt() *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *WeChatBindingUpsertOne) SetUserID(v int64) *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WeChatBindingUpsertOne) UpdateUserID() *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateUserID()
	})
}

// SetAppID sets the "app_id" field.
func (u *WeChatBindingUpsertOne) SetAppID(v string) *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *WeChatBindingUpsertOne) UpdateAppID() *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateAppID()
	})
}

// SetOpenid sets the "openid" field.
func (u *WeChatBindingUpsertOne) SetOpenid(v string) *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetOpenid(v)
	})
}

// UpdateOpenid sets the "openid" field to the value that was provided on create.
func (u *WeChatBindingUpsertOne) UpdateOpenid() *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateOpenid()
	})
}

// SetUnionid sets the "unionid" field.
func (u *WeChatBindingUpsertOne) SetUnionid(v string) *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetUnionid(v)
	})
}

// UpdateUnionid sets the "unionid" field to the value that was provided on create.
func (u *WeChatBindingUpsertOne) UpdateUnionid() *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateUnionid()
	})
}

// ClearUnionid clears the value of the "unionid" field.
func (u *WeChatBindingUpsertOne) ClearUnionid() *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.ClearUnionid()
	})
}

// SetSubscribed sets the "subscribed" field.
func (u *WeChatBindingUpsertOne) SetSubscribed(v bool) *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetSubscribed(v)
	})
}

// UpdateSubscribed sets the "subscribed" field to the value that was provided on create.
func (u *WeChatBindingUpsertOne) UpdateSubscribed() *WeChatBindingUpsertOne {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateSubscribed()
	})
}

// Exec executes the query.
func (u *WeChatBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WeChatBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WeChatBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WeChatBindingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WeChatBindingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WeChatBindingCreateBulk is the builder for creating many WeChatBinding entities in bulk.
type WeChatBindingCreateBulk struct {
	config
	err      error
	builders []*WeChatBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the WeChatBinding entities in the database.
func (_c *WeChatBindingCreateBulk) Save(ctx context.Context) ([]*WeChatBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WeChatBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WeChatBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WeChatBindingCreateBulk) SaveX(ctx context.Context) []*WeChatBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WeChatBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WeChatBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WeChatBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WeChatBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WeChatBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *WeChatBindingUpsertBulk {
	_c.conflict = opts
	return &WeChatBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WeChatBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WeChatBindingCreateBulk) OnConflictColumns(columns ...string) *WeChatBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WeChatBindingUpsertBulk{
		create: _c,
	}
}

// WeChatBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of WeChatBinding nodes.
type WeChatBindingUpsertBulk struct {
	create *WeChatBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WeChatBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WeChatBindingUpsertBulk) UpdateNewValues() *WeChatBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(wechatbinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WeChatBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WeChatBindingUpsertBulk) Ignore() *WeChatBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WeChatBindingUpsertBulk) DoNothing() *WeChatBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WeChatBindingCreateBulk.OnConflict
// documentation for more info.
func (u *WeChatBindingUpsertBulk) Update(set func(*WeChatBindingUpsert)) *WeChatBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WeChatBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WeChatBindingUpsertBulk) SetUpdatedAt(v time.Time) *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WeChatBindingUpsertBulk) UpdateUpdatedAt() *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *WeChatBindingUpsertBulk) SetUserID(v int64) *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WeChatBindingUpsertBulk) UpdateUserID() *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateUserID()
	})
}

// SetAppID sets the "app_id" field.
func (u *WeChatBindingUpsertBulk) SetAppID(v string) *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *WeChatBindingUpsertBulk) UpdateAppID() *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateAppID()
	})
}

// SetOpenid sets the "openid" field.
func (u *WeChatBindingUpsertBulk) SetOpenid(v string) *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetOpenid(v)
	})
}

// UpdateOpenid sets the "openid" field to the value that was provided on create.
func (u *WeChatBindingUpsertBulk) UpdateOpenid() *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateOpenid()
	})
}

// SetUnionid sets the "unionid" field.
func (u *WeChatBindingUpsertBulk) SetUnionid(v string) *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetUnionid(v)
	})
}

// UpdateUnionid sets the "unionid" field to the value that was provided on create.
func (u *WeChatBindingUpsertBulk) UpdateUnionid() *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateUnionid()
	})
}

// ClearUnionid clears the value of the "unionid" field.
func (u *WeChatBindingUpsertBulk) ClearUnionid() *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.ClearUnionid()
	})
}

// SetSubscribed sets the "subscribed" field.
func (u *WeChatBindingUpsertBulk) SetSubscribed(v bool) *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.SetSubscribed(v)
	})
}

// UpdateSubscribed sets the "subscribed" field to the value that was provided on create.
func (u *WeChatBindingUpsertBulk) UpdateSubscribed() *WeChatBindingUpsertBulk {
	return u.Update(func(s *WeChatBindingUpsert) {
		s.UpdateSubscribed()
	})
}

// Exec executes the query.
func (u *WeChatBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WeChatBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WeChatBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WeChatBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
