// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/wechatbindinghistory"
)

// WeChatBindingHistory is the model entity for the WeChatBindingHistory schema.
type WeChatBindingHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID string `json:"app_id,omitempty"`
	// Openid holds the value of the "openid" field.
	Openid string `json:"openid,omitempty"`
	// UnboundAt holds the value of the "unbound_at" field.
	UnboundAt time.Time `json:"unbound_at,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason       string `json:"reason,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WeChatBindingHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wechatbindinghistory.FieldID, wechatbindinghistory.FieldUserID:
			values[i] = new(sql.NullInt64)
		case wechatbindinghistory.FieldAppID, wechatbindinghistory.FieldOpenid, wechatbindinghistory.FieldReason:
			values[i] = new(sql.NullString)
		case wechatbindinghistory.FieldCreatedAt, wechatbindinghistory.FieldUpdatedAt, wechatbindinghistory.FieldUnboundAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WeChatBindingHistory fields.
func (_m *WeChatBindingHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wechatbindinghistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case wechatbindinghistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case wechatbindinghistory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case wechatbindinghistory.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case wechatbindinghistory.FieldAppID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				_m.AppID = value.String
			}
		case wechatbindinghistory.FieldOpenid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field openid", values[i])
			} else if value.Valid {
				_m.Openid = value.String
			}
		case wechatbindinghistory.FieldUnboundAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field unbound_at", values[i])
			} else if value.Valid {
				_m.UnboundAt = value.Time
			}
		case wechatbindinghistory.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WeChatBindingHistory.
// This includes values selected through modifiers, order, etc.
func (_m *WeChatBindingHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WeChatBindingHistory.
// Note that you need to call WeChatBindingHistory.Unwrap() before calling this method if this WeChatBindingHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WeChatBindingHistory) Update() *WeChatBindingHistoryUpdateOne {
	return NewWeChatBindingHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WeChatBindingHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WeChatBindingHistory) Unwrap() *WeChatBindingHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WeChatBindingHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WeChatBindingHistory) String() string {
	var builder strings.Builder
	builder.WriteString("WeChatBindingHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(_m.AppID)
	builder.WriteString(", ")
	builder.WriteString("openid=")
	builder.WriteString(_m.Openid)
	builder.WriteString(", ")
	builder.WriteString("unbound_at=")
	builder.WriteString(_m.UnboundAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteByte(')')
	return builder.String()
}

// WeChatBindingHistories is a parsable slice of WeChatBindingHistory.
type WeChatBindingHistories []*WeChatBindingHistory
