// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/wechatbindinghistory"
)

// WeChatBindingHistoryDelete is the builder for deleting a WeChatBindingHistory entity.
type WeChatBindingHistoryDelete struct {
	config
	hooks    []Hook
	mutation *WeChatBindingHistoryMutation
}

// Where appends a list predicates to the WeChatBindingHistoryDelete builder.
func (_d *WeChatBindingHistoryDelete) Where(ps ...predicate.WeChatBindingHistory) *WeChatBindingHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WeChatBindingHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WeChatBindingHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WeChatBindingHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(wechatbindinghistory.Table, sqlgraph.NewFieldSpec(wechatbindinghistory.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WeChatBindingHistoryDeleteOne is the builder for deleting a single WeChatBindingHistory entity.
type WeChatBindingHistoryDeleteOne struct {
	_d *WeChatBindingHistoryDelete
}

// Where appends a list predicates to the WeChatBindingHistoryDelete builder.
func (_d *WeChatBindingHistoryDeleteOne) Where(ps ...predicate.WeChatBindingHistory) *WeChatBindingHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WeChatBindingHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{wechatbindinghistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WeChatBindingHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
