// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/wechatbindinghistory"
)

// WeChatBindingHistoryUpdate is the builder for updating WeChatBindingHistory entities.
type WeChatBindingHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *WeChatBindingHistoryMutation
}

// Where appends a list predicates to the WeChatBindingHistoryUpdate builder.
func (_u *WeChatBindingHistoryUpdate) Where(ps ...predicate.WeChatBindingHistory) *WeChatBindingHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WeChatBindingHistoryUpdate) SetUpdatedAt(v time.Time) *WeChatBindingHistoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WeChatBindingHistoryUpdate) SetUserID(v int64) *WeChatBindingHistoryUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WeChatBindingHistoryUpdate) SetNillableUserID(v *int64) *WeChatBindingHistoryUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *WeChatBindingHistoryUpdate) AddUserID(v int64) *WeChatBindingHistoryUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *WeChatBindingHistoryUpdate) SetAppID(v string) *WeChatBindingHistoryUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *WeChatBindingHistoryUpdate) SetNillableAppID(v *string) *WeChatBindingHistoryUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetOpenid sets the "openid" field.
func (_u *WeChatBindingHistoryUpdate) SetOpenid(v string) *WeChatBindingHistoryUpdate {
	_u.mutation.SetOpenid(v)
	return _u
}

// SetNillableOpenid sets the "openid" field if the given value is not nil.
func (_u *WeChatBindingHistoryUpdate) SetNillableOpenid(v *string) *WeChatBindingHistoryUpdate {
	if v != nil {
		_u.SetOpenid(*v)
	}
	return _u
}

// SetUnboundAt sets the "unbound_at" field.
func (_u *WeChatBindingHistoryUpdate) SetUnboundAt(v time.Time) *WeChatBindingHistoryUpdate {
	_u.mutation.SetUnboundAt(v)
	return _u
}

// SetNillableUnboundAt sets the "unbound_at" field if the given value is not nil.
func (_u *WeChatBindingHistoryUpdate) SetNillableUnboundAt(v *time.Time) *WeChatBindingHistoryUpdate {
	if v != nil {
		_u.SetUnboundAt(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *WeChatBindingHistoryUpdate) SetReason(v string) *WeChatBindingHistoryUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *WeChatBindingHistoryUpdate) SetNillableReason(v *string) *WeChatBindingHistoryUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// Mutation returns the WeChatBindingHistoryMutation object of the builder.
func (_u *WeChatBindingHistoryUpdate) Mutation() *WeChatBindingHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WeChatBindingHistoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WeChatBindingHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WeChatBindingHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WeChatBindingHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WeChatBindingHistoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wechatbindinghistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WeChatBindingHistoryUpdate) check() error {
	if v, ok := _u.mutation.AppID(); ok {
		if err := wechatbindinghistory.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "WeChatBindingHistory.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Openid(); ok {
		if err := wechatbindinghistory.OpenidValidator(v); err != nil {
			return &ValidationError{Name: "openid", err: fmt.Errorf(`ent: validator failed for field "WeChatBindingHistory.openid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := wechatbindinghistory.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "WeChatBindingHistory.reason": %w`, err)}
		}
	}
	return nil
}

func (_u *WeChatBindingHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wechatbindinghistory.Table, wechatbindinghistory.Columns, sqlgraph.NewFieldSpec(wechatbindinghistory.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wechatbindinghistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(wechatbindinghistory.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(wechatbindinghistory.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(wechatbindinghistory.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Openid(); ok {
		_spec.SetField(wechatbindinghistory.FieldOpenid, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnboundAt(); ok {
		_spec.SetField(wechatbindinghistory.FieldUnboundAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(wechatbindinghistory.FieldReason, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wechatbindinghistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WeChatBindingHistoryUpdateOne is the builder for updating a single WeChatBindingHistory entity.
type WeChatBindingHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WeChatBindingHistoryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WeChatBindingHistoryUpdateOne) SetUpdatedAt(v time.Time) *WeChatBindingHistoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WeChatBindingHistoryUpdateOne) SetUserID(v int64) *WeChatBindingHistoryUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WeChatBindingHistoryUpdateOne) SetNillableUserID(v *int64) *WeChatBindingHistoryUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *WeChatBindingHistoryUpdateOne) AddUserID(v int64) *WeChatBindingHistoryUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *WeChatBindingHistoryUpdateOne) SetAppID(v string) *WeChatBindingHistoryUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *WeChatBindingHistoryUpdateOne) SetNillableAppID(v *string) *WeChatBindingHistoryUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetOpenid sets the "openid" field.
func (_u *WeChatBindingHistoryUpdateOne) SetOpenid(v string) *WeChatBindingHistoryUpdateOne {
	_u.mutation.SetOpenid(v)
	return _u
}

// SetNillableOpenid sets the "openid" field if the given value is not nil.
func (_u *WeChatBindingHistoryUpdateOne) SetNillableOpenid(v *string) *WeChatBindingHistoryUpdateOne {
	if v != nil {
		_u.SetOpenid(*v)
	}
	return _u
}

// SetUnboundAt sets the "unbound_at" field.
func (_u *WeChatBindingHistoryUpdateOne) SetUnboundAt(v time.Time) *WeChatBindingHistoryUpdateOne {
	_u.mutation.SetUnboundAt(v)
	return _u
}

// SetNillableUnboundAt sets the "unbound_at" field if the given value is not nil.
func (_u *WeChatBindingHistoryUpdateOne) SetNillableUnboundAt(v *time.Time) *WeChatBindingHistoryUpdateOne {
	if v != nil {
		_u.SetUnboundAt(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *WeChatBindingHistoryUpdateOne) SetReason(v string) *WeChatBindingHistoryUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *WeChatBindingHistoryUpdateOne) SetNillableReason(v *string) *WeChatBindingHistoryUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// Mutation returns the WeChatBindingHistoryMutation object of the builder.
func (_u *WeChatBindingHistoryUpdateOne) Mutation() *WeChatBindingHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the WeChatBindingHistoryUpdate builder.
func (_u *WeChatBindingHistoryUpdateOne) Where(ps ...predicate.WeChatBindingHistory) *WeChatBindingHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WeChatBindingHistoryUpdateOne) Select(field string, fields ...string) *WeChatBindingHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WeChatBindingHistory entity.
func (_u *WeChatBindingHistoryUpdateOne) Save(ctx context.Context) (*WeChatBindingHistory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WeChatBindingHistoryUpdateOne) SaveX(ctx context.Context) *WeChatBindingHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WeChatBindingHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WeChatBindingHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WeChatBindingHistoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wechatbindinghistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WeChatBindingHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.AppID(); ok {
		if err := wechatbindinghistory.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "WeChatBindingHistory.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Openid(); ok {
		if err := wechatbindinghistory.OpenidValidator(v); err != nil {
			return &ValidationError{Name: "openid", err: fmt.Errorf(`ent: validator failed for field "WeChatBindingHistory.openid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := wechatbindinghistory.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "WeChatBindingHistory.reason": %w`, err)}
		}
	}
	return nil
}

func (_u *WeChatBindingHistoryUpdateOne) sqlSave(ctx context.Context) (_node *WeChatBindingHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wechatbindinghistory.Table, wechatbindinghistory.Columns, sqlgraph.NewFieldSpec(wechatbindinghistory.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WeChatBindingHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wechatbindinghistory.FieldID)
		for _, f := range fields {
			if !wechatbindinghistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wechatbindinghistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wechatbindinghistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(wechatbindinghistory.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(wechatbindinghistory.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(wechatbindinghistory.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Openid(); ok {
		_spec.SetField(wechatbindinghistory.FieldOpenid, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnboundAt(); ok {
		_spec.SetField(wechatbindinghistory.FieldUnboundAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(wechatbindinghistory.FieldReason, field.TypeString, value)
	}
	_node = &WeChatBindingHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wechatbindinghistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
