// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/wechatbinding"
)

// WeChatBinding is the model entity for the WeChatBinding schema.
type WeChatBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID string `json:"app_id,omitempty"`
	// Openid holds the value of the "openid" field.
	Openid string `json:"openid,omitempty"`
	// Unionid holds the value of the "unionid" field.
	Unionid *string `json:"unionid,omitempty"`
	// Subscribed holds the value of the "subscribed" field.
	Subscribed bool `json:"subscribed,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WeChatBindingQuery when eager-loading is set.
	Edges        WeChatBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WeChatBindingEdges holds the relations/edges for other nodes in the graph.
type WeChatBindingEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WeChatBindingEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WeChatBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wechatbinding.FieldSubscribed:
			values[i] = new(sql.NullBool)
		case wechatbinding.FieldID, wechatbinding.FieldUserID:
			values[i] = new(sql.NullInt64)
		case wechatbinding.FieldAppID, wechatbinding.FieldOpenid, wechatbinding.FieldUnionid:
			values[i] = new(sql.NullString)
		case wechatbinding.FieldCreatedAt, wechatbinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WeChatBinding fields.
func (_m *WeChatBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wechatbinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case wechatbinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case wechatbinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case wechatbinding.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case wechatbinding.FieldAppID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				_m.AppID = value.String
			}
		case wechatbinding.FieldOpenid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field openid", values[i])
			} else if value.Valid {
				_m.Openid = value.String
			}
		case wechatbinding.FieldUnionid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unionid", values[i])
			} else if value.Valid {
				_m.Unionid = new(string)
				*_m.Unionid = value.String
			}
		case wechatbinding.FieldSubscribed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field subscribed", values[i])
			} else if value.Valid {
				_m.Subscribed = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WeChatBinding.
// This includes values selected through modifiers, order, etc.
func (_m *WeChatBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the WeChatBinding entity.
func (_m *WeChatBinding) QueryUser() *UserQuery {
	return NewWeChatBindingClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this WeChatBinding.
// Note that you need to call WeChatBinding.Unwrap() before calling this method if this WeChatBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WeChatBinding) Update() *WeChatBindingUpdateOne {
	return NewWeChatBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WeChatBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WeChatBinding) Unwrap() *WeChatBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WeChatBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WeChatBinding) String() string {
	var builder strings.Builder
	builder.WriteString("WeChatBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(_m.AppID)
	builder.WriteString(", ")
	builder.WriteString("openid=")
	builder.WriteString(_m.Openid)
	builder.WriteString(", ")
	if v := _m.Unionid; v != nil {
		builder.WriteString("unionid=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("subscribed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Subscribed))
	builder.WriteByte(')')
	return builder.String()
}

// WeChatBindings is a parsable slice of WeChatBinding.
type WeChatBindings []*WeChatBinding
