// Code generated by ent, DO NOT EDIT.

package wechatbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the wechatbinding type in the database.
	Label = "we_chat_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldOpenid holds the string denoting the openid field in the database.
	FieldOpenid = "openid"
	// FieldUnionid holds the string denoting the unionid field in the database.
	FieldUnionid = "unionid"
	// FieldSubscribed holds the string denoting the subscribed field in the database.
	FieldSubscribed = "subscribed"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the wechatbinding in the database.
	Table = "wechat_bindings"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "wechat_bindings"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for wechatbinding fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldAppID,
	FieldOpenid,
	FieldUnionid,
	FieldSubscribed,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// AppIDValidator is a validator for the "app_id" field. It is called by the builders before save.
	AppIDValidator func(string) error
	// OpenidValidator is a validator for the "openid" field. It is called by the builders before save.
	OpenidValidator func(string) error
	// UnionidValidator is a validator for the "unionid" field. It is called by the builders before save.
	UnionidValidator func(string) error
	// DefaultSubscribed holds the default value on creation for the "subscribed" field.
	DefaultSubscribed bool
)

// OrderOption defines the ordering options for the WeChatBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAppID orders the results by the app_id field.
func ByAppID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppID, opts...).ToFunc()
}

// ByOpenid orders the results by the openid field.
func ByOpenid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpenid, opts...).ToFunc()
}

// ByUnionid orders the results by the unionid field.
func ByUnionid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnionid, opts...).ToFunc()
}

// BySubscribed orders the results by the subscribed field.
func BySubscribed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscribed, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
