// Code generated by ent, DO NOT EDIT.

package wechatbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldUserID, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldAppID, v))
}

// Openid applies equality check predicate on the "openid" field. It's identical to OpenidEQ.
func Openid(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldOpenid, v))
}

// Unionid applies equality check predicate on the "unionid" field. It's identical to UnionidEQ.
func Unionid(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldUnionid, v))
}

// Subscribed applies equality check predicate on the "subscribed" field. It's identical to SubscribedEQ.
func Subscribed(v bool) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldSubscribed, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNotIn(FieldUserID, vs...))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLTE(FieldAppID, v))
}

// AppIDContains applies the Contains predicate on the "app_id" field.
func AppIDContains(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldContains(FieldAppID, v))
}

// AppIDHasPrefix applies the HasPrefix predicate on the "app_id" field.
func AppIDHasPrefix(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldHasPrefix(FieldAppID, v))
}

// AppIDHasSuffix applies the HasSuffix predicate on the "app_id" field.
func AppIDHasSuffix(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldHasSuffix(FieldAppID, v))
}

// AppIDEqualFold applies the EqualFold predicate on the "app_id" field.
func AppIDEqualFold(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEqualFold(FieldAppID, v))
}

// AppIDContainsFold applies the ContainsFold predicate on the "app_id" field.
func AppIDContainsFold(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldContainsFold(FieldAppID, v))
}

// OpenidEQ applies the EQ predicate on the "openid" field.
func OpenidEQ(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldOpenid, v))
}

// OpenidNEQ applies the NEQ predicate on the "openid" field.
func OpenidNEQ(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNEQ(FieldOpenid, v))
}

// OpenidIn applies the In predicate on the "openid" field.
func OpenidIn(vs ...string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldIn(FieldOpenid, vs...))
}

// OpenidNotIn applies the NotIn predicate on the "openid" field.
func OpenidNotIn(vs ...string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNotIn(FieldOpenid, vs...))
}

// OpenidGT applies the GT predicate on the "openid" field.
func OpenidGT(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGT(FieldOpenid, v))
}

// OpenidGTE applies the GTE predicate on the "openid" field.
func OpenidGTE(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGTE(FieldOpenid, v))
}

// OpenidLT applies the LT predicate on the "openid" field.
func OpenidLT(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLT(FieldOpenid, v))
}

// OpenidLTE applies the LTE predicate on the "openid" field.
func OpenidLTE(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLTE(FieldOpenid, v))
}

// OpenidContains applies the Contains predicate on the "openid" field.
func OpenidContains(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldContains(FieldOpenid, v))
}

// OpenidHasPrefix applies the HasPrefix predicate on the "openid" field.
func OpenidHasPrefix(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldHasPrefix(FieldOpenid, v))
}

// OpenidHasSuffix applies the HasSuffix predicate on the "openid" field.
func OpenidHasSuffix(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldHasSuffix(FieldOpenid, v))
}

// OpenidEqualFold applies the EqualFold predicate on the "openid" field.
func OpenidEqualFold(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEqualFold(FieldOpenid, v))
}

// OpenidContainsFold applies the ContainsFold predicate on the "openid" field.
func OpenidContainsFold(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldContainsFold(FieldOpenid, v))
}

// UnionidEQ applies the EQ predicate on the "unionid" field.
func UnionidEQ(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldUnionid, v))
}

// UnionidNEQ applies the NEQ predicate on the "unionid" field.
func UnionidNEQ(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNEQ(FieldUnionid, v))
}

// UnionidIn applies the In predicate on the "unionid" field.
func UnionidIn(vs ...string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldIn(FieldUnionid, vs...))
}

// UnionidNotIn applies the NotIn predicate on the "unionid" field.
func UnionidNotIn(vs ...string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNotIn(FieldUnionid, vs...))
}

// UnionidGT applies the GT predicate on the "unionid" field.
func UnionidGT(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGT(FieldUnionid, v))
}

// UnionidGTE applies the GTE predicate on the "unionid" field.
func UnionidGTE(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldGTE(FieldUnionid, v))
}

// UnionidLT applies the LT predicate on the "unionid" field.
func UnionidLT(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLT(FieldUnionid, v))
}

// UnionidLTE applies the LTE predicate on the "unionid" field.
func UnionidLTE(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldLTE(FieldUnionid, v))
}

// UnionidContains applies the Contains predicate on the "unionid" field.
func UnionidContains(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldContains(FieldUnionid, v))
}

// UnionidHasPrefix applies the HasPrefix predicate on the "unionid" field.
func UnionidHasPrefix(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldHasPrefix(FieldUnionid, v))
}

// UnionidHasSuffix applies the HasSuffix predicate on the "unionid" field.
func UnionidHasSuffix(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldHasSuffix(FieldUnionid, v))
}

// UnionidIsNil applies the IsNil predicate on the "unionid" field.
func UnionidIsNil() predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldIsNull(FieldUnionid))
}

// UnionidNotNil applies the NotNil predicate on the "unionid" field.
func UnionidNotNil() predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNotNull(FieldUnionid))
}

// UnionidEqualFold applies the EqualFold predicate on the "unionid" field.
func UnionidEqualFold(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEqualFold(FieldUnionid, v))
}

// UnionidContainsFold applies the ContainsFold predicate on the "unionid" field.
func UnionidContainsFold(v string) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldContainsFold(FieldUnionid, v))
}

// SubscribedEQ applies the EQ predicate on the "subscribed" field.
func SubscribedEQ(v bool) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldEQ(FieldSubscribed, v))
}

// SubscribedNEQ applies the NEQ predicate on the "subscribed" field.
func SubscribedNEQ(v bool) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.FieldNEQ(FieldSubscribed, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.WeChatBinding {
	return predicate.WeChatBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.WeChatBinding {
	return predicate.WeChatBinding(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WeChatBinding) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WeChatBinding) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WeChatBinding) predicate.WeChatBinding {
	return predicate.WeChatBinding(sql.NotPredicates(p))
}
